version: 2.1

orbs:
  # init basics orbs for install and config node.js, aws cli and eb cli
  aws-cli: circleci/aws-cli@3.1.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@5.0.2
# Declare CI/CD jobs.
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - node/install
      - checkout
      # install NPM packages for Front-End
      - run:
          name: Install Front-End Packages
          command: npm run frontend:install
      # Build Front-End
      - run:
          name: Build Front-End
          command: npm run frontend:build
      # Deploy Front-End
      - run:
          name: Deploy Front-End
          command: npm run frontend:deploy
      # install NPM packages for Back-End
      - run:
          name: Install Back-End Packages
          command: npm run backend:install
      # Build Back-End
      - run:
          name: Build Back-End
          command: npm run backend:build
      # Deploy Back-End
      - run:
          name: Deploy Back-End
          command: npm run backend:deploy
